/**
 * Third-party domain → provider mapping
 * Used for carbon attribution and GDPR categorisation of network requests.
 * This supplements the Wappalyzer database which focuses on tech fingerprinting,
 * not per-domain request attribution.
 */

export interface ThirdPartyDomainInfo {
  name: string;
  category: string;
  gdprCategory: 'essential' | 'functional' | 'tracking' | 'advertising';
  privacySafeAlternative?: string;
}

export const THIRD_PARTY_DOMAINS: Record<string, ThirdPartyDomainInfo> = {
  // ── Analytics ─────────────────────────────────────────────────────────────
  'google-analytics.com': { name: 'Google Analytics', category: 'analytics', gdprCategory: 'tracking', privacySafeAlternative: 'Plausible, Fathom, Umami' },
  'analytics.google.com': { name: 'Google Analytics 4', category: 'analytics', gdprCategory: 'tracking', privacySafeAlternative: 'Plausible, Fathom' },
  'googletagmanager.com': { name: 'Google Tag Manager', category: 'tag-manager', gdprCategory: 'tracking' },
  'googletagservices.com': { name: 'Google Tag Services', category: 'tag-manager', gdprCategory: 'tracking' },
  'hotjar.com': { name: 'Hotjar', category: 'analytics', gdprCategory: 'tracking', privacySafeAlternative: 'Microsoft Clarity (basic) or self-hosted Matomo' },
  'static.hotjar.com': { name: 'Hotjar', category: 'analytics', gdprCategory: 'tracking' },
  'mixpanel.com': { name: 'Mixpanel', category: 'analytics', gdprCategory: 'tracking', privacySafeAlternative: 'PostHog (self-hosted)' },
  'cdn.mxpnl.com': { name: 'Mixpanel CDN', category: 'analytics', gdprCategory: 'tracking' },
  'amplitude.com': { name: 'Amplitude', category: 'analytics', gdprCategory: 'tracking', privacySafeAlternative: 'PostHog (self-hosted)' },
  'cdn.amplitude.com': { name: 'Amplitude CDN', category: 'analytics', gdprCategory: 'tracking' },
  'segment.com': { name: 'Segment', category: 'analytics', gdprCategory: 'tracking' },
  'cdn.segment.com': { name: 'Segment CDN', category: 'analytics', gdprCategory: 'tracking' },
  'api.segment.io': { name: 'Segment API', category: 'analytics', gdprCategory: 'tracking' },
  'heapanalytics.com': { name: 'Heap Analytics', category: 'analytics', gdprCategory: 'tracking' },
  'fullstory.com': { name: 'FullStory', category: 'analytics', gdprCategory: 'tracking' },
  'edge.fullstory.com': { name: 'FullStory Edge', category: 'analytics', gdprCategory: 'tracking' },
  'logrocket.com': { name: 'LogRocket', category: 'analytics', gdprCategory: 'tracking' },
  'posthog.com': { name: 'PostHog (Cloud)', category: 'analytics', gdprCategory: 'tracking' },
  'us.i.posthog.com': { name: 'PostHog US', category: 'analytics', gdprCategory: 'tracking' },
  'eu.i.posthog.com': { name: 'PostHog EU', category: 'analytics', gdprCategory: 'tracking' },
  'clarity.ms': { name: 'Microsoft Clarity', category: 'analytics', gdprCategory: 'tracking' },
  'mouseflow.com': { name: 'Mouseflow', category: 'analytics', gdprCategory: 'tracking' },
  'smartlook.com': { name: 'Smartlook', category: 'analytics', gdprCategory: 'tracking' },
  'rec.smartlook.com': { name: 'Smartlook Recording', category: 'analytics', gdprCategory: 'tracking' },
  'mc.yandex.ru': { name: 'Yandex.Metrica', category: 'analytics', gdprCategory: 'tracking' },
  'mc.yandex.com': { name: 'Yandex.Metrica', category: 'analytics', gdprCategory: 'tracking' },
  'plausible.io': { name: 'Plausible Analytics', category: 'analytics', gdprCategory: 'essential' },
  'simpleanalytics.com': { name: 'Simple Analytics', category: 'analytics', gdprCategory: 'essential' },
  'simpleanalyticscdn.com': { name: 'Simple Analytics CDN', category: 'analytics', gdprCategory: 'essential' },
  'fathom.com': { name: 'Fathom Analytics', category: 'analytics', gdprCategory: 'essential' },
  'cdn.usefathom.com': { name: 'Fathom Analytics CDN', category: 'analytics', gdprCategory: 'essential' },
  'umami.is': { name: 'Umami', category: 'analytics', gdprCategory: 'essential' },
  'matomo.cloud': { name: 'Matomo Cloud', category: 'analytics', gdprCategory: 'tracking' },
  'piwik.pro': { name: 'Piwik PRO', category: 'analytics', gdprCategory: 'tracking' },
  'clicky.com': { name: 'Clicky', category: 'analytics', gdprCategory: 'tracking' },
  'statcounter.com': { name: 'StatCounter', category: 'analytics', gdprCategory: 'tracking' },
  'woopra.com': { name: 'Woopra', category: 'analytics', gdprCategory: 'tracking' },
  'kissmetrics.com': { name: 'Kissmetrics', category: 'analytics', gdprCategory: 'tracking' },
  'appcues.com': { name: 'Appcues', category: 'analytics', gdprCategory: 'tracking' },
  'cdn.appcues.com': { name: 'Appcues CDN', category: 'analytics', gdprCategory: 'tracking' },

  // ── Advertising & Retargeting ─────────────────────────────────────────────
  'doubleclick.net': { name: 'Google DoubleClick', category: 'advertising', gdprCategory: 'advertising' },
  'googlesyndication.com': { name: 'Google AdSense', category: 'advertising', gdprCategory: 'advertising' },
  'googleadservices.com': { name: 'Google Ad Services', category: 'advertising', gdprCategory: 'advertising' },
  'google.com': { name: 'Google Services', category: 'advertising', gdprCategory: 'advertising' },
  'facebook.net': { name: 'Facebook Pixel', category: 'advertising', gdprCategory: 'advertising' },
  'connect.facebook.net': { name: 'Facebook SDK', category: 'advertising', gdprCategory: 'advertising' },
  'analytics.tiktok.com': { name: 'TikTok Pixel', category: 'advertising', gdprCategory: 'advertising' },
  'business.tiktok.com': { name: 'TikTok Business', category: 'advertising', gdprCategory: 'advertising' },
  'static.ads-twitter.com': { name: 'Twitter Ads', category: 'advertising', gdprCategory: 'advertising' },
  'ads-twitter.com': { name: 'Twitter Ads', category: 'advertising', gdprCategory: 'advertising' },
  'outbrain.com': { name: 'Outbrain', category: 'advertising', gdprCategory: 'advertising' },
  'widgets.outbrain.com': { name: 'Outbrain Widgets', category: 'advertising', gdprCategory: 'advertising' },
  'taboola.com': { name: 'Taboola', category: 'advertising', gdprCategory: 'advertising' },
  'cdn.taboola.com': { name: 'Taboola CDN', category: 'advertising', gdprCategory: 'advertising' },
  'criteo.com': { name: 'Criteo', category: 'advertising', gdprCategory: 'advertising' },
  'static.criteo.net': { name: 'Criteo CDN', category: 'advertising', gdprCategory: 'advertising' },
  'amazon-adsystem.com': { name: 'Amazon Ads', category: 'advertising', gdprCategory: 'advertising' },
  'adsrvr.org': { name: 'The Trade Desk', category: 'advertising', gdprCategory: 'advertising' },
  'adroll.com': { name: 'AdRoll', category: 'advertising', gdprCategory: 'advertising' },
  'd.adroll.com': { name: 'AdRoll', category: 'advertising', gdprCategory: 'advertising' },
  'pubmatic.com': { name: 'PubMatic', category: 'advertising', gdprCategory: 'advertising' },
  'rubiconproject.com': { name: 'Magnite (Rubicon)', category: 'advertising', gdprCategory: 'advertising' },
  'openx.net': { name: 'OpenX', category: 'advertising', gdprCategory: 'advertising' },
  'appnexus.com': { name: 'Xandr (AppNexus)', category: 'advertising', gdprCategory: 'advertising' },
  'advertising.com': { name: 'Advertising.com', category: 'advertising', gdprCategory: 'advertising' },
  'indexexchange.com': { name: 'Index Exchange', category: 'advertising', gdprCategory: 'advertising' },
  'sharethis.com': { name: 'ShareThis', category: 'advertising', gdprCategory: 'advertising' },
  'platform.twitter.com': { name: 'Twitter Platform', category: 'social', gdprCategory: 'tracking' },
  'static.pincdn.com': { name: 'Pinterest CDN', category: 'social', gdprCategory: 'tracking' },
  'assets.pinterest.com': { name: 'Pinterest Assets', category: 'social', gdprCategory: 'tracking' },
  'ct.pinterest.com': { name: 'Pinterest Tag', category: 'advertising', gdprCategory: 'advertising' },
  'sc-static.net': { name: 'Snapchat CDN', category: 'advertising', gdprCategory: 'advertising' },
  'tr.snapchat.com': { name: 'Snapchat Pixel', category: 'advertising', gdprCategory: 'advertising' },
  'linkedin.com': { name: 'LinkedIn Insight Tag', category: 'advertising', gdprCategory: 'advertising' },
  'snap.licdn.com': { name: 'LinkedIn Insight', category: 'advertising', gdprCategory: 'advertising' },
  'bat.bing.com': { name: 'Microsoft Ads (Bing)', category: 'advertising', gdprCategory: 'advertising' },

  // ── Fonts ─────────────────────────────────────────────────────────────────
  'fonts.googleapis.com': { name: 'Google Fonts', category: 'fonts', gdprCategory: 'functional', privacySafeAlternative: 'Self-host fonts or use Fontsource (npm)' },
  'fonts.gstatic.com': { name: 'Google Fonts (Assets)', category: 'fonts', gdprCategory: 'functional', privacySafeAlternative: 'Self-host fonts' },
  'use.typekit.net': { name: 'Adobe Fonts (Typekit)', category: 'fonts', gdprCategory: 'functional', privacySafeAlternative: 'Self-host fonts' },
  'kit.fontawesome.com': { name: 'Font Awesome Kit', category: 'fonts', gdprCategory: 'functional', privacySafeAlternative: 'Self-host Font Awesome or use Lucide/Heroicons' },
  'use.fontawesome.com': { name: 'Font Awesome CDN', category: 'fonts', gdprCategory: 'functional' },
  'pro.fontawesome.com': { name: 'Font Awesome Pro', category: 'fonts', gdprCategory: 'functional' },
  'fast.fonts.net': { name: 'Monotype Fonts', category: 'fonts', gdprCategory: 'functional' },
  'cloud.typography.com': { name: 'Hoefler & Co Fonts', category: 'fonts', gdprCategory: 'functional' },
  'fonts.bunny.net': { name: 'Bunny Fonts (Privacy-friendly Google Fonts proxy)', category: 'fonts', gdprCategory: 'essential' },

  // ── Video ─────────────────────────────────────────────────────────────────
  'youtube.com': { name: 'YouTube', category: 'video', gdprCategory: 'functional', privacySafeAlternative: 'youtube-nocookie.com embed' },
  'youtube-nocookie.com': { name: 'YouTube (Privacy Enhanced)', category: 'video', gdprCategory: 'functional' },
  'ytimg.com': { name: 'YouTube (Assets)', category: 'video', gdprCategory: 'functional' },
  'googlevideo.com': { name: 'YouTube (Video)', category: 'video', gdprCategory: 'functional' },
  'vimeo.com': { name: 'Vimeo', category: 'video', gdprCategory: 'functional' },
  'vimeocdn.com': { name: 'Vimeo CDN', category: 'video', gdprCategory: 'functional' },
  'i.vimeocdn.com': { name: 'Vimeo Images', category: 'video', gdprCategory: 'functional' },
  'fast.wistia.net': { name: 'Wistia', category: 'video', gdprCategory: 'functional' },
  'wistia.com': { name: 'Wistia', category: 'video', gdprCategory: 'functional' },
  'embed.wistia.com': { name: 'Wistia Embed', category: 'video', gdprCategory: 'functional' },
  'loom.com': { name: 'Loom', category: 'video', gdprCategory: 'functional' },
  'cdn.loom.com': { name: 'Loom CDN', category: 'video', gdprCategory: 'functional' },
  'player.vdocipher.com': { name: 'VdoCipher', category: 'video', gdprCategory: 'functional' },
  'cdn.jwplayer.com': { name: 'JW Player', category: 'video', gdprCategory: 'functional' },
  'content.jwplatform.com': { name: 'JW Platform', category: 'video', gdprCategory: 'functional' },
  'brightcove.net': { name: 'Brightcove', category: 'video', gdprCategory: 'functional' },
  'players.brightcove.net': { name: 'Brightcove Players', category: 'video', gdprCategory: 'functional' },
  'mux.com': { name: 'Mux', category: 'video', gdprCategory: 'functional' },
  'stream.mux.com': { name: 'Mux Stream', category: 'video', gdprCategory: 'functional' },
  'cloudflarestream.com': { name: 'Cloudflare Stream', category: 'video', gdprCategory: 'functional' },

  // ── Maps ──────────────────────────────────────────────────────────────────
  'maps.googleapis.com': { name: 'Google Maps', category: 'maps', gdprCategory: 'functional', privacySafeAlternative: 'OpenStreetMap + Leaflet.js (self-hosted)' },
  'maps.gstatic.com': { name: 'Google Maps (Assets)', category: 'maps', gdprCategory: 'functional' },
  'api.mapbox.com': { name: 'Mapbox', category: 'maps', gdprCategory: 'functional' },
  'events.mapbox.com': { name: 'Mapbox Events', category: 'maps', gdprCategory: 'tracking' },
  'nominatim.openstreetmap.org': { name: 'OpenStreetMap Nominatim', category: 'maps', gdprCategory: 'essential' },
  'tile.openstreetmap.org': { name: 'OpenStreetMap Tiles', category: 'maps', gdprCategory: 'essential' },
  'here.com': { name: 'HERE Maps', category: 'maps', gdprCategory: 'functional' },

  // ── Payment ───────────────────────────────────────────────────────────────
  'js.stripe.com': { name: 'Stripe.js', category: 'payment', gdprCategory: 'essential' },
  'm.stripe.com': { name: 'Stripe Fraud Prevention', category: 'payment', gdprCategory: 'essential' },
  'm.stripe.network': { name: 'Stripe Network', category: 'payment', gdprCategory: 'essential' },
  'js.paypalobjects.com': { name: 'PayPal SDK', category: 'payment', gdprCategory: 'essential' },
  'www.paypalobjects.com': { name: 'PayPal Assets', category: 'payment', gdprCategory: 'essential' },
  'paypal.com': { name: 'PayPal', category: 'payment', gdprCategory: 'essential' },
  'braintreegateway.com': { name: 'Braintree', category: 'payment', gdprCategory: 'essential' },
  'assets.braintreegateway.com': { name: 'Braintree Assets', category: 'payment', gdprCategory: 'essential' },
  'pay.google.com': { name: 'Google Pay', category: 'payment', gdprCategory: 'essential' },
  'js.squareupsandbox.com': { name: 'Square Sandbox', category: 'payment', gdprCategory: 'essential' },
  'web.squarecdn.com': { name: 'Square CDN', category: 'payment', gdprCategory: 'essential' },
  'js.klarna.com': { name: 'Klarna', category: 'payment', gdprCategory: 'essential' },
  'x.klarnacdn.net': { name: 'Klarna CDN', category: 'payment', gdprCategory: 'essential' },
  'static.afterpay.com': { name: 'Afterpay', category: 'payment', gdprCategory: 'essential' },
  'cdn.affirm.com': { name: 'Affirm', category: 'payment', gdprCategory: 'essential' },
  'checkout.razorpay.com': { name: 'Razorpay', category: 'payment', gdprCategory: 'essential' },
  'cdn.mollie.com': { name: 'Mollie', category: 'payment', gdprCategory: 'essential' },
  'cdn.adyen.com': { name: 'Adyen', category: 'payment', gdprCategory: 'essential' },

  // ── Chat / Support ────────────────────────────────────────────────────────
  'js.intercomcdn.com': { name: 'Intercom', category: 'chat', gdprCategory: 'functional' },
  'widget.intercom.io': { name: 'Intercom Widget', category: 'chat', gdprCategory: 'functional' },
  'nexus.intercom.io': { name: 'Intercom Nexus', category: 'chat', gdprCategory: 'functional' },
  'static.zdassets.com': { name: 'Zendesk Widget', category: 'chat', gdprCategory: 'functional' },
  'ekr.zdassets.com': { name: 'Zendesk Auth', category: 'chat', gdprCategory: 'functional' },
  'chat.drift.com': { name: 'Drift', category: 'chat', gdprCategory: 'functional' },
  'js.driftt.com': { name: 'Drift CDN', category: 'chat', gdprCategory: 'functional' },
  'embed.tawk.to': { name: 'Tawk.to', category: 'chat', gdprCategory: 'functional' },
  'va.tawk.to': { name: 'Tawk.to API', category: 'chat', gdprCategory: 'functional' },
  'code.tidio.co': { name: 'Tidio', category: 'chat', gdprCategory: 'functional' },
  'widget.tidio.co': { name: 'Tidio Widget', category: 'chat', gdprCategory: 'functional' },
  'client.crisp.chat': { name: 'Crisp', category: 'chat', gdprCategory: 'functional' },
  'storage.crisp.chat': { name: 'Crisp Storage', category: 'chat', gdprCategory: 'functional' },
  'wchat.freshchat.com': { name: 'Freshchat', category: 'chat', gdprCategory: 'functional' },
  'fw-cdn.com': { name: 'Freshworks CDN', category: 'chat', gdprCategory: 'functional' },
  'assets.freshdesk.com': { name: 'Freshdesk', category: 'chat', gdprCategory: 'functional' },
  'widget.freshworks.com': { name: 'Freshworks Widget', category: 'chat', gdprCategory: 'functional' },
  'chat.hubspot.com': { name: 'HubSpot Chat', category: 'chat', gdprCategory: 'functional' },
  'static.livechatinc.com': { name: 'LiveChat', category: 'chat', gdprCategory: 'functional' },
  'cdn.livechatinc.com': { name: 'LiveChat CDN', category: 'chat', gdprCategory: 'functional' },
  'olark.com': { name: 'Olark', category: 'chat', gdprCategory: 'functional' },
  'chatra.io': { name: 'Chatra', category: 'chat', gdprCategory: 'functional' },
  'call.chatra.io': { name: 'Chatra API', category: 'chat', gdprCategory: 'functional' },
  'app.acquire.io': { name: 'Acquire.io', category: 'chat', gdprCategory: 'functional' },
  'help.bolddesk.com': { name: 'BoldDesk', category: 'chat', gdprCategory: 'functional' },

  // ── CRM & Marketing ──────────────────────────────────────────────────────
  'js.hsforms.net': { name: 'HubSpot Forms', category: 'crm', gdprCategory: 'functional' },
  'track.hubspot.com': { name: 'HubSpot Tracking', category: 'crm', gdprCategory: 'tracking' },
  'forms.hubspot.com': { name: 'HubSpot Forms API', category: 'crm', gdprCategory: 'functional' },
  'munchkin.marketo.net': { name: 'Marketo Munchkin', category: 'crm', gdprCategory: 'tracking' },
  'chimpstatic.com': { name: 'Mailchimp', category: 'crm', gdprCategory: 'functional' },
  'static.klaviyo.com': { name: 'Klaviyo', category: 'crm', gdprCategory: 'functional' },
  'a.klaviyo.com': { name: 'Klaviyo API', category: 'crm', gdprCategory: 'tracking' },
  'salesforce.com': { name: 'Salesforce', category: 'crm', gdprCategory: 'functional' },
  'cdn.pardot.com': { name: 'Pardot (Salesforce)', category: 'crm', gdprCategory: 'tracking' },
  'pi.pardot.com': { name: 'Pardot Tracking', category: 'crm', gdprCategory: 'tracking' },
  'cdn.activecampaign.com': { name: 'ActiveCampaign', category: 'crm', gdprCategory: 'functional' },
  'trackcmp.net': { name: 'ActiveCampaign Tracking', category: 'crm', gdprCategory: 'tracking' },
  'emailjs.com': { name: 'EmailJS', category: 'crm', gdprCategory: 'functional' },
  'sendgrid.net': { name: 'SendGrid', category: 'crm', gdprCategory: 'functional' },
  'brevo.com': { name: 'Brevo (Sendinblue)', category: 'crm', gdprCategory: 'functional' },
  'drip.com': { name: 'Drip', category: 'crm', gdprCategory: 'tracking' },
  'tag.getdrip.com': { name: 'Drip Tag', category: 'crm', gdprCategory: 'tracking' },
  'js.convertkit.com': { name: 'ConvertKit', category: 'crm', gdprCategory: 'functional' },

  // ── Error Tracking / APM ─────────────────────────────────────────────────
  'browser.sentry-cdn.com': { name: 'Sentry', category: 'apm', gdprCategory: 'essential' },
  'o.sentry-cdn.com': { name: 'Sentry CDN', category: 'apm', gdprCategory: 'essential' },
  'cdn.rollbar.com': { name: 'Rollbar', category: 'apm', gdprCategory: 'essential' },
  'js-agent.newrelic.com': { name: 'New Relic', category: 'apm', gdprCategory: 'essential' },
  'bam.nr-data.net': { name: 'New Relic Data', category: 'apm', gdprCategory: 'essential' },
  'bugsnag.com': { name: 'Bugsnag', category: 'apm', gdprCategory: 'essential' },
  'd2wy8f7a9ursnm.cloudfront.net': { name: 'Bugsnag CDN', category: 'apm', gdprCategory: 'essential' },
  'cdn.ravenjs.com': { name: 'Raven.js (Sentry legacy)', category: 'apm', gdprCategory: 'essential' },
  'cdn4.usefathom.com': { name: 'Fathom Errors', category: 'apm', gdprCategory: 'essential' },
  'datadog-logs-us.com': { name: 'Datadog Logs', category: 'apm', gdprCategory: 'essential' },
  'browser-intake-datadoghq.com': { name: 'Datadog RUM', category: 'apm', gdprCategory: 'essential' },

  // ── Auth ─────────────────────────────────────────────────────────────────
  'cdn.auth0.com': { name: 'Auth0', category: 'auth', gdprCategory: 'essential' },
  'cdn.okta.com': { name: 'Okta', category: 'auth', gdprCategory: 'essential' },
  'global.oktacdn.com': { name: 'Okta CDN', category: 'auth', gdprCategory: 'essential' },
  'accounts.google.com': { name: 'Google Sign-In', category: 'auth', gdprCategory: 'essential' },
  'apis.google.com': { name: 'Google APIs', category: 'auth', gdprCategory: 'essential' },
  'appleid.cdn-apple.com': { name: 'Sign in with Apple', category: 'auth', gdprCategory: 'essential' },
  'connect.facebook.com': { name: 'Facebook Login', category: 'auth', gdprCategory: 'essential' },
  'clerk.com': { name: 'Clerk', category: 'auth', gdprCategory: 'essential' },
  'supabase.co': { name: 'Supabase Auth', category: 'auth', gdprCategory: 'essential' },
  'recaptcha.net': { name: 'Google reCAPTCHA', category: 'security', gdprCategory: 'essential' },
  'js.hcaptcha.com': { name: 'hCaptcha', category: 'security', gdprCategory: 'essential' },
  'challenges.cloudflare.com': { name: 'Cloudflare Turnstile', category: 'security', gdprCategory: 'essential' },

  // ── CDN ──────────────────────────────────────────────────────────────────
  'cdnjs.cloudflare.com': { name: 'Cloudflare CDN (cdnjs)', category: 'cdn', gdprCategory: 'essential' },
  'cdn.jsdelivr.net': { name: 'jsDelivr CDN', category: 'cdn', gdprCategory: 'essential' },
  'unpkg.com': { name: 'unpkg CDN', category: 'cdn', gdprCategory: 'essential' },
  'ajax.googleapis.com': { name: 'Google Hosted Libraries', category: 'cdn', gdprCategory: 'essential' },
  'ajax.aspnetcdn.com': { name: 'Microsoft CDN', category: 'cdn', gdprCategory: 'essential' },
  'maxcdn.bootstrapcdn.com': { name: 'Bootstrap CDN', category: 'cdn', gdprCategory: 'essential' },
  'stackpath.bootstrapcdn.com': { name: 'Bootstrap CDN (StackPath)', category: 'cdn', gdprCategory: 'essential' },
  'code.jquery.com': { name: 'jQuery CDN', category: 'cdn', gdprCategory: 'essential' },
  'd3js.org': { name: 'D3.js CDN', category: 'cdn', gdprCategory: 'essential' },

  // ── A/B Testing & Personalisation ────────────────────────────────────────
  'optimizely.com': { name: 'Optimizely', category: 'ab-testing', gdprCategory: 'functional' },
  'cdn.optimizely.com': { name: 'Optimizely CDN', category: 'ab-testing', gdprCategory: 'functional' },
  'dev.visualwebsiteoptimizer.com': { name: 'VWO', category: 'ab-testing', gdprCategory: 'functional' },
  'abtest.biz': { name: 'A/B Test', category: 'ab-testing', gdprCategory: 'functional' },
  'cdn.convertexperiences.com': { name: 'Convert', category: 'ab-testing', gdprCategory: 'functional' },
  'variation.com': { name: 'Variation.com', category: 'ab-testing', gdprCategory: 'functional' },
  'launchdarkly.com': { name: 'LaunchDarkly', category: 'feature-flags', gdprCategory: 'essential' },
  'app.launchdarkly.com': { name: 'LaunchDarkly API', category: 'feature-flags', gdprCategory: 'essential' },
  'growthbook.io': { name: 'GrowthBook', category: 'ab-testing', gdprCategory: 'functional' },

  // ── Consent Management ────────────────────────────────────────────────────
  'cdn.cookielaw.org': { name: 'OneTrust', category: 'cookie-compliance', gdprCategory: 'essential' },
  'optanon.com': { name: 'OneTrust', category: 'cookie-compliance', gdprCategory: 'essential' },
  'consent.cookiebot.com': { name: 'Cookiebot', category: 'cookie-compliance', gdprCategory: 'essential' },
  'cdn.cookiepro.com': { name: 'CookiePro', category: 'cookie-compliance', gdprCategory: 'essential' },
  'quantcast.mgr.consensu.org': { name: 'Quantcast CMP', category: 'cookie-compliance', gdprCategory: 'essential' },
  'cdn.privacy-center.org': { name: 'Sourcepoint', category: 'cookie-compliance', gdprCategory: 'essential' },
  'consent.trustarc.com': { name: 'TrustArc', category: 'cookie-compliance', gdprCategory: 'essential' },
  'app.termly.io': { name: 'Termly', category: 'cookie-compliance', gdprCategory: 'essential' },
  'cdn.iubenda.com': { name: 'iubenda', category: 'cookie-compliance', gdprCategory: 'essential' },
  'iubenda.com': { name: 'iubenda', category: 'cookie-compliance', gdprCategory: 'essential' },

  // ── Review Platforms ──────────────────────────────────────────────────────
  'widget.trustpilot.com': { name: 'Trustpilot', category: 'reviews', gdprCategory: 'functional' },
  'invitations-api.trustpilot.com': { name: 'Trustpilot API', category: 'reviews', gdprCategory: 'functional' },
  'staticw2.yotpo.com': { name: 'Yotpo', category: 'reviews', gdprCategory: 'functional' },
  'api.yotpo.com': { name: 'Yotpo API', category: 'reviews', gdprCategory: 'functional' },
  'cdn.judge.me': { name: 'Judge.me', category: 'reviews', gdprCategory: 'functional' },
  'cdn.reviews.co.uk': { name: 'Reviews.co.uk', category: 'reviews', gdprCategory: 'functional' },
  'badge.reviews.io': { name: 'Reviews.io', category: 'reviews', gdprCategory: 'functional' },
  'powerreviews.com': { name: 'PowerReviews', category: 'reviews', gdprCategory: 'functional' },
  'display.bazaarvoice.com': { name: 'Bazaarvoice', category: 'reviews', gdprCategory: 'functional' },

  // ── Search ────────────────────────────────────────────────────────────────
  'cdn.algolia.net': { name: 'Algolia CDN', category: 'search', gdprCategory: 'essential' },
  'algolianet.com': { name: 'Algolia', category: 'search', gdprCategory: 'essential' },
  'algolia.net': { name: 'Algolia API', category: 'search', gdprCategory: 'essential' },
  'search.doofinder.com': { name: 'Doofinder', category: 'search', gdprCategory: 'functional' },

  // ── Social Widgets ────────────────────────────────────────────────────────
  'platform.linkedin.com': { name: 'LinkedIn Plugin', category: 'social', gdprCategory: 'tracking' },
  'buttons.github.io': { name: 'GitHub Buttons', category: 'social', gdprCategory: 'essential' },
  'badgen.net': { name: 'Badgen', category: 'social', gdprCategory: 'essential' },
  'shields.io': { name: 'Shields.io', category: 'social', gdprCategory: 'essential' },

  // ── Shipping ─────────────────────────────────────────────────────────────
  'www.ups.com': { name: 'UPS', category: 'shipping', gdprCategory: 'essential' },
  'www.fedex.com': { name: 'FedEx', category: 'shipping', gdprCategory: 'essential' },
  'www.dhl.com': { name: 'DHL', category: 'shipping', gdprCategory: 'essential' },

  // ── Miscellaneous functional ──────────────────────────────────────────────
  'translate.googleapis.com': { name: 'Google Translate', category: 'translation', gdprCategory: 'functional' },
  'translate.google.com': { name: 'Google Translate', category: 'translation', gdprCategory: 'functional' },
  'www.google.com': { name: 'Google Services', category: 'miscellaneous', gdprCategory: 'functional' },
  'cookie-cdn.cookiepro.com': { name: 'CookiePro', category: 'cookie-compliance', gdprCategory: 'essential' },
};

// Category → GDPR lookup for green hosting / carbon data
export const CARBON_INTENSITY_BY_COUNTRY: Record<string, number> = {
  'IS': 25, 'NO': 28, 'PY': 30, 'SE': 41, 'FR': 56, 'CH': 45,
  'AT': 148, 'CA': 120, 'NZ': 115, 'DE': 385, 'GB': 233, 'EU': 276,
  'JP': 471, 'KR': 415, 'US': 386, 'CN': 555, 'IN': 700, 'AU': 510,
  'NL': 295, 'BE': 172, 'ES': 208, 'IT': 340, 'PL': 635, 'CZ': 497,
  'FI': 67, 'DK': 166, 'IE': 290, 'PT': 131, 'RU': 331, 'BR': 127,
  'MX': 449, 'ZA': 700, 'SG': 409, 'TH': 449, 'VN': 350, 'ID': 713,
  'PH': 533, 'MY': 585, '__default': 442,
};

export const GREEN_HOSTING_PROVIDERS: Record<string, {
  green: boolean | 'partial'; method: string; percentage?: number; note?: string;
}> = {
  'google': { green: true, method: 'PPAs + offsets + on-site', percentage: 64 },
  'google-cloud': { green: true, method: 'PPAs + offsets', percentage: 64 },
  'aws': { green: 'partial', method: 'RECs (matched, not direct)', percentage: 100, note: '100% renewable via RECs' },
  'amazon': { green: 'partial', method: 'RECs', percentage: 100 },
  'microsoft': { green: true, method: 'PPAs + RECs', percentage: 100 },
  'azure': { green: true, method: 'PPAs + RECs', percentage: 100 },
  'hetzner': { green: true, method: 'Direct renewable (hydro + wind)', percentage: 100 },
  'scaleway': { green: true, method: 'Hydro power (France)', percentage: 100 },
  'ovh': { green: 'partial', method: 'Partial renewable', percentage: 50 },
  'netlify': { green: true, method: 'Carbon neutral + renewable', percentage: 100 },
  'vercel': { green: true, method: 'Carbon neutral', percentage: 100 },
  'cloudflare': { green: true, method: 'Carbon neutral + RE committed', percentage: 100 },
  'digitalocean': { green: true, method: 'RECs', percentage: 100 },
  'linode': { green: 'partial', method: 'RECs in some regions', percentage: 50 },
  'fastly': { green: 'partial', method: 'RECs + offset', percentage: 100 },
  'akamai': { green: true, method: 'Carbon neutral operations', percentage: 100 },
  'fly.io': { green: 'partial', method: 'Renewable in select regions', percentage: 60 },
  'railway': { green: 'partial', method: 'Partial renewable', percentage: 50 },
  'render': { green: 'partial', method: 'RECs', percentage: 100 },
};
